remote_theme: "jekyll/minima@1e8a445"

title: "Arya Fotouhi | Cybersecurity Portfolio"
description: "Security Analyst focused on threat detection, vulnerability management, endpoint security, and practical homelab projects."

minima:
  skin: dark
  hide_site_feed_link: true

  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/afotouhi/" }
    - { platform: github, user_url: "https://github.com/afotouhi-cyber" }
    
header_pages:
  - about.md
  - index.md
  - projects.md
  - resume.md
